version: '3.8'
services:
  db:
    image: "postgres" # use latest official postgres version
    env_file:
      - db.env # configure postgres
    volumes:
      - db-data:/var/lib/postgresql/data # persist data even if container shuts down
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
  
networks:
  backend:

volumes:
  db-data: