version: '3.8'
services:
  db:
    image: "postgres"
    env_file:
      - db.env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
  
networks:
  backend:

volumes:
  db-data: